# Generated by Django 5.2.1 on 2025-05-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='senha_gov',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='SenhaGov'),
        ),
    ]
